#!/usr/bin/env bash
set -e

QUERY_ANALYZE_BASE='
	query ($owner: String!, $repo: String!) {
	  repository(owner:$owner, name:$repo) {
	    name
	    owner {
	      login
	    }
	    defaultBranchRef {
	      branchProtectionRule {
	        requiresCodeOwnerReviews
	        requiredApprovingReviewCount
	      }
	    }
	    codeowners {
	      errors {
	        kind
	        suggestion
	        source
	        path
	        message
	        line
	        column
	      }
	    }
	    objectCodeownersGithub: object(expression: "HEAD:.github/CODEOWNERS") {
	      ... on Blob {
	        text
	        byteSize
	        abbreviatedOid
	      }
	    }
	    objectCodeOwnersRoot: object(expression: "HEAD:CODEOWNERS") {
	      ... on Blob {
	        text
	        byteSize
	        abbreviatedOid
	      }
	    }
	  }
	}
'

QUERY_ANALYZE_ACCESS='
	query ($owner: String!, $repo: String!, $affiliation: CollaboratorAffiliation!, $endCursor: String) {
	  repository(owner:$owner, name:$repo) {
	    name
	    owner {
	      login
	    }
	    collaborators(first: 100, affiliation: $affiliation, after: $endCursor) {
	      pageInfo {
	        endCursor
	        hasNextPage
	      }
	      edges {
	        node {
	          login
	        }
	        permission
	        permissionSources {
	          permission
	          source {
	            ... on Team {
	              type: __typename
	              name: slug
	            }
	            ... on Repository {
	              type: __typename
	              name: name
	            }
	            ... on Organization {
	              type: __typename
	              name: login
	            }
	          }
	        }
	      }
	    }
	  }
	}
'

function analyze_repo() {
	local REPO="$1"
	echo "$OWNER/$REPO:  analyze repository"

	# Capture branch protection rules around codeowners are setup on default branch and codeowner errors
	FILE_ANALYZE_BASE="$CACHEDIR/$OWNER-$REPO-base.json"

	if ! test -f "$FILE_ANALYZE_BASE"; then
		echo "$OWNER/$REPO:  pulling repository codeowner errors and branch protection"
		gh api graphql -f query="${QUERY_ANALYZE_BASE}" -F owner=$OWNER -F repo=$REPO >> $FILE_ANALYZE_BASE
	else
		echo "$OWNER/$REPO:  skip pulling repository codeowner errors and branch protection"
	fi

	# Pull repository collaborators
	FILE_ANALYZE_ACCESS="$CACHEDIR/$OWNER-$REPO-access.json"

	if ! test -f "$FILE_ANALYZE_ACCESS"; then
		echo "$OWNER/$REPO:  pulling repository collaborators"
		gh api graphql -f query="${QUERY_ANALYZE_ACCESS}" -F owner=$OWNER -F repo=$REPO -F affiliation=DIRECT --paginate >> $FILE_ANALYZE_ACCESS
	else
		echo "$OWNER/$REPO:  skip pulling repository collaborators"
	fi

	# Extract branch protection rule and codeowner data for report from cache
	CODEOWNER_ERRORS=$(jq '.data.repository.codeowners.errors | length' $FILE_ANALYZE_BASE)
	CODEOWNERS_GITHUB_EXISTS=$(jq '.data.repository.objectCodeownersGithub? | has("abbreviatedOid")' $FILE_ANALYZE_BASE)
	CODEOWNERS_ROOT_EXISTS=$(jq '.data.repository.objectCodeOwnersRoot? | has("abbreviatedOid")' $FILE_ANALYZE_BASE)

    BPR_EXISTS=$(jq '.data.repository.defaultBranchRef?.branchProtectionRule? | if . == null then false else true end' $FILE_ANALYZE_BASE)
    BPR_CODEOWNERS_REQUIRED=$(jq '.data.repository.defaultBranchRef?.branchProtectionRule?.requiresCodeOwnerReviews // false' $FILE_ANALYZE_BASE)
    BPR_CODEOWNERS_REVIEWS=$(jq '.data.repository.defaultBranchRef?.branchProtectionRule?.requiredApprovingReviewCount // 0' $FILE_ANALYZE_BASE)

	echo "$OWNER/$REPO:  output results; CODEOWNERS_GITHUB_EXISTS=$CODEOWNERS_GITHUB_EXISTS, CODEOWNERS_ROOT_EXISTS=$CODEOWNERS_ROOT_EXISTS, CODEOWNER_ERRORS=$CODEOWNER_ERRORS, BPR_EXISTS=$BPR_EXISTS, BPR_CODEOWNERS_REQUIRED=$BPR_CODEOWNERS_REQUIRED, BPR_CODEOWNERS_REVIEWS=$BPR_CODEOWNERS_REVIEWS"
	printf "%s\n" $OWNER $REPO $CODEOWNERS_GITHUB_EXISTS $CODEOWNERS_ROOT_EXISTS $CODEOWNER_ERRORS $BPR_EXISTS $BPR_CODEOWNERS_REQUIRED $BPR_CODEOWNERS_REVIEWS | paste -sd ',' - >> $OUTPUTFILE_BASE

	# Extract repository collaborator access sources for report from cache
	jq -rs '.[].data.repository as $repo | $repo.collaborators.edges[] | . as $collaborator | $collaborator.permissionSources[] | [$repo.owner.login, $repo.name, $collaborator.node.login, $collaborator.permission, .source.type, .source.name, .permission] | @csv' $FILE_ANALYZE_ACCESS >> $OUTPUTFILE_ACCESS

}

FORCE=false
CACHEDIR=
OWNER=
OUTPUTFILE_ACCESS=
OUTPUTFILE_BASE=
PRESERVE=false
REPO=

__USAGE="
Analyze GitHub repository codeowners and branch protection rules.

USAGE
  $(basename $0) [options] <owner>
  $(basename $0) [options] <owner>/<repo>

FLAGS
  -a, --output-access <output-file>   Name of GitHub report containing repository access, without '.csv' extension
  -b, --output-base <output-file>     Name of GitHub report containing codeowner and default branch protection rule, without '.csv' extension
  -c, --cache-dir <cache-dir>         Name of directory containing preserved data to reuse
  -d, --debug                         Enable debugging
  -f, --force                         Whether to overwrite output file if it exists
  -h, --help                          Displays help usage
  -p, --preserve                      Preserve temporary directory containing data
";

die() {
	printf "\nError: %s\n" "$1"
	echo "$__USAGE"
	exit 1
}

if ! type -p gh > /dev/null; then
	die "'gh' could not be found"
fi

if ! type -p jq > /dev/null; then
	die "'jq' could not be found"
fi

while getopts "a:b:c:dfhp-:" OPT; do
	if [ "$OPT" = "-" ]; then    # long option: reformulate OPT and OPTARG
		OPT="${OPTARG%%=*}"      # extract long option name
		OPTARG="${OPTARG#$OPT}"	 # extract long option argument (may be empty)
		OPTARG="${OPTARG#=}"     # if long option argument, remove assigning `=`
	fi

	case "$OPT" in

		output-access | a)
			OUTPUTFILE_ACCESS="${OPTARG}.csv"
			;;

		output-base | b)
			OUTPUTFILE_BASE="${OPTARG}.csv"
			;;

		cache-dir | c)
			CACHEDIR="${OPTARG}"
			;;

		debug | d)
			set -x
			;;

		force | f)
			FORCE=true
			;;

		help | h)
			echo "$__USAGE"
			exit 0
			;;

		preserve | p)
			PRESERVE=true
			;;
	esac
done

# shift so that $@, $1, etc. refer to the non-option arguments
shift "$((OPTIND-1))"

if [ -z "$1" ]; then
	die "Must provide owner or owner/repo"
elif [[ "$1" == *"/"* ]]; then
	OWNER=$(echo $1 | cut -d '/' -f 1)
	REPO=$(echo $1 | cut -d '/' -f 2)

	if [ -z "${OUTPUTFILE_ACCESS}" ]; then
		OUTPUTFILE_ACCESS="$OWNER-$REPO.access.csv"
	fi

	if [ -z "${OUTPUTFILE_BASE}" ]; then
		OUTPUTFILE_BASE="$OWNER-$REPO.base.csv"
	fi
else
	OWNER="$1"

	if [ -z "${OUTPUTFILE_ACCESS}" ]; then
		OUTPUTFILE_ACCESS="$OWNER.access.csv"
	fi

	if [ -z "${OUTPUTFILE_BASE}" ]; then
		OUTPUTFILE_BASE="$OWNER.base.csv"
	fi
fi

# Handle situation if previous report file exists
if test -f "$OUTPUTFILE_ACCESS"; then

	if ! $FORCE; then
		die "$OUTPUTFILE_ACCESS exists; -f, --force will delete if exists"
	fi

	echo "Deleting previous report file:  $OUTPUTFILE_ACCESS"
	rm -f $OUTPUTFILE_ACCESS
fi

if test -f "$OUTPUTFILE_BASE"; then

	if ! $FORCE; then
		die "$OUTPUTFILE_BASE exists; -f, --force will delete if exists"
	fi

	echo "Deleting previous report file:  $OUTPUTFILE_BASE"
	rm -f $OUTPUTFILE_BASE
fi

# Prepare temporary working directory for caching data
if test -d "$CACHEDIR"; then
	echo "Using existing directory for caching data:  $CACHEDIR"
elif [ -z "$CACHEDIR" ]; then
	CACHEDIR="$(mktemp -d -t gh-codeowner-analysisXXX)"
	echo "Created temporary directory for caching data:  $CACHEDIR"

	if ! $PRESERVE; then
		trap 'rm -rf -- "$CACHEDIR"' EXIT
	fi
else
	mkdir -p $CACHEDIR
	echo "Created directory for caching data:  $CACHEDIR"
fi

# Begin analyzing repositories
printf "%s\n" 'OWNER' 'REPO' 'CODEOWNERS_GITHUB_EXISTS' 'CODEOWNERS_ROOT_EXISTS' 'CODEOWNER_ERRORS' 'BPR_EXISTS' 'BPR_CODEOWNERS_REQUIRED' 'BPR_CODEOWNERS_REVIEWS' | paste -sd ',' - > $OUTPUTFILE_BASE
printf "%s\n" 'OWNER' 'REPO' 'USER_LOGIN' 'USER_PERMISSION' 'SOURCE_TYPE' 'SOURCE_NAME' 'SOURCE_PERMISSION' | paste -sd ',' - > $OUTPUTFILE_ACCESS

if [ -z "${REPO}" ]; then
	echo "$OWNER:  pulling repositories for analysis"

	QUERY='
		query ($owner: String!, $endCursor: String) {
		  repositoryOwner(login: $owner) {
		    repositories(first: 100, after: $endCursor) {
		      pageInfo {
		        endCursor
		        hasNextPage
		      }
		      nodes {
		        name
		      }
		    }
		  }
		}
	'

	for repo in $(gh api graphql -f query="${QUERY}" -F owner="$OWNER" --paginate --jq '.data.repositoryOwner.repositories.nodes[].name'); do
		analyze_repo "$repo"
	done
else
	analyze_repo "$REPO"
fi
